name: android testing 
on:
  push:
    branches: 
      - master
      - github-actions
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WiseTrack
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: run unit tests
        run: ./gradlew testDebugUnitTest